### ISSUE TITLE
[bug] `PeekPoke: Too many files are open`

### ISSUE THREAD

**Issue by tl-flavio-barinas** [erickrenz/peekpoke#1]
Programs with many reads/writes continuously open `file descriptors` to `/dev/mem` without closing them, eventually leading to a crash: `Too many files are open`. Looking at the `c` implementation of both `peek` and `poke`, I found that the `file descriptors` are never closed. 

Fix:
Close the `file descriptor` at the end of both the `peek` and `poke` calls.

**Comment by erickrenz** [comment]
fixed in commit 6a547f12597344db70074e0d61d6bf71a75796cd
released with v0.3.0
